name: Deploy to GitHub Pages on dev branch

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Delete gh-pages branch
        run: git push origin --delete gh-pages || true

      - name: Install dependencies
        run: npm ci

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}
        run: npm run deploy:gh-pages
